FROM node:alpine AS builder

# Set working directory
WORKDIR '/dafis'
# Install require module
RUN apk update && apk add g++ make bash zlib-dev libpng-dev libtool automake autoconf nasm && rm -fr /var/cache/apk/*
# Copy NPM Package
COPY 'package.json' .
RUN npm install
RUN npm install nodemon -g
COPY . .

# Run command
CMD ["nodemon", "-L"]
